name: Node.js CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    name: Unit Test Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ./node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-npm-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-npm-
      - name: NPM Install
        run: yarn install
      - name: Run Unit Tests
        run: yarn test
      - name: Run Coverage Test
        run: yarn run coverage
        env:
          CI: true
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ./node_modules # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-npm-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-npm-
      - name: NPM Install
        run: yarn install
      - name: Run Lint Test
        run: yarn run lint
        env:
          CI: true
